#!/bin/sh

cp fluid_patch_fltk-1.1.4.diff ~/
cd ~
path=$(find -name fltk-1.1.4 | head -n 1)
echo "Path of fltk sourcecode: $path"
echo -n "Is this correct? [yn] "
read a
if test $a = "n" 
then 
	echo -n "Path to fltk sourcecode: "
	read path
fi
cp fluid_patch_fltk-1.1.4.diff $path
cd $path
patch -p0 < fluid_patch_fltk-1.1.4.diff
echo "Patch applied."
cd fluid
make
echo "We need root password to install fluid."
su -c "make install"
cd ~
rm -f fluid_patch_fltk-1.1.4.diff

