// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "pref_form.h"
int text_size;
int save_window_size;
int auto_hide;

Fl_Double_Window *pref_window=(Fl_Double_Window *)0;

Fl_Button *pref_ok_btn=(Fl_Button *)0;

static void cb_pref_ok_btn(Fl_Button*, void*) {
  text_size = text_size_choice->value() * 2 + 6;
save_window_size = save_wsoe_check->value();
auto_hide = hide_output_check->value();
pref_window->hide();
}

Fl_Button *pref_cancel_btn=(Fl_Button *)0;

static void cb_pref_cancel_btn(Fl_Button*, void*) {
  pref_window->hide();
}

Fl_Choice *text_size_choice=(Fl_Choice *)0;

Fl_Check_Button *smart_indent_check=(Fl_Check_Button *)0;

Fl_Check_Button *save_wsoe_check=(Fl_Check_Button *)0;

Fl_Check_Button *hide_output_check=(Fl_Check_Button *)0;

Fl_Check_Button *rec_pr_check=(Fl_Check_Button *)0;

Fl_Double_Window* make_pref_form() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = pref_window = new Fl_Double_Window(529, 331, "Preferences");
    w = o;
    o->align(FL_ALIGN_TOP_LEFT);
    { Fl_Button* o = pref_ok_btn = new Fl_Button(345, 295, 85, 25, "OK");
      o->callback((Fl_Callback*)cb_pref_ok_btn);
    }
    { Fl_Button* o = pref_cancel_btn = new Fl_Button(435, 295, 80, 25, "Cancel");
      o->callback((Fl_Callback*)cb_pref_cancel_btn);
    }
    { Fl_Choice* o = text_size_choice = new Fl_Choice(95, 35, 60, 25, "Text Size");
      o->down_box(FL_BORDER_BOX);
      text_size_choice->add("6");text_size_choice->add("8");text_size_choice->add("10");text_size_choice->add("12");text_size_choice->add("14");text_size_choice->add("16");text_size_choice->add("18");text_size_choice->add("20");
      text_size_choice->value(3);
    }
    { Fl_Check_Button* o = smart_indent_check = new Fl_Check_Button(30, 65, 180, 25, "Use Smart-Indent Option");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = save_wsoe_check = new Fl_Check_Button(30, 90, 195, 25, "Save Window Size On Exit");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = hide_output_check = new Fl_Check_Button(30, 115, 195, 25, "Auto-hide Output Window");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = rec_pr_check = new Fl_Check_Button(30, 140, 235, 25, "Open previous project on startup");
      o->down_box(FL_DOWN_BOX);
    }
    o->set_modal();
    o->end();
  }
  return w;
}
