/*
    FLDev - FLTK Integrated Development Environment
    Copyright (C) 2005-2016  Philipp Pracht, Georg Potthast, Neil McNeight

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef proj_wiz_form_h
#define proj_wiz_form_h
#include <FL/Fl.H>
#include <FL/Fl_Native_File_Chooser.H>
#include "Fl_Dev_Util.h";
#include "globals.h"
extern bool pr_wiz_ok; 
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *proj_wiz;
#include <FL/Fl_Input.H>
extern Fl_Input *pr_dir_input;
#include <FL/Fl_Button.H>
extern Fl_Button *pr_wiz_browse_btn;
extern Fl_Input *pr_name_input;
extern Fl_Button *pr_wiz_ok_btn;
extern Fl_Button *pr_wiz_cancel_btn;
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *x_app;
extern Fl_Round_Button *con_app;
extern Fl_Round_Button *lib_static;
extern Fl_Round_Button *lib_shared;
extern Fl_Input *pr_own_makefile;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *main_cpp_chk;
extern Fl_Check_Button *own_make_chk;
Fl_Double_Window* make_proj_wizard();
#endif
